[[trees]]
kind = "Corner"
px = 75.71437286062176
py = 3.799626774634839
pz = 44.669

[[trees]]
kind = "Wilg"
px = 81.86569954275821
py = 5.757227962335097
pz = 43.57

[[trees]]
kind = "Wilg"
px = 80.85796149933832
py = 10.78228047450674
pz = 43.231

[[trees]]
kind = "Wilg"
px = 81.38663905754983
py = 14.670438145429198
pz = 43.239

[[trees]]
kind = "Wilg"
px = 81.11691079717839
py = 19.881874313581577
pz = 42.943

[[trees]]
kind = "Wilg"
px = 77.10731564318992
py = 22.579615812133362
pz = 43.131

[[trees]]
kind = "Fruit"
px = 84.22292928125313
py = 17.943419226618207
pz = 43.101

[[trees]]
kind = "Fruit"
px = 83.58330658768017
py = 13.569773100979635
pz = 43.671

[[trees]]
kind = "Hole"
px = 87.14296447303298
py = 13.163005835040767
pz = 45.46

[[trees]]
kind = "Appelboom"
px = 88.3279849440471
py = 14.704810711175332
pz = 45.271

[[trees]]
kind = "Beukenboom"
px = 90.22716344713211
py = 17.441084630163566
pz = 44.275

[[trees]]
kind = "Beukenboom"
px = 93.12112172912327
py = 14.768678981424475
pz = 43.06

[[trees]]
kind = "Kersenboom"
px = 96.53977106047164
py = 15.422126097925737
pz = 42.099

[[trees]]
kind = "Kersenboom"
px = 95.4939037114217
py = 9.148146544979474
pz = 43.521

[[trees]]
kind = "Fruit"
px = 102.71900479774949
py = 8.724356014258934
pz = 45.065

[[trees]]
kind = "Fruit"
px = 102.99415944881007
py = 16.300247883663783
pz = 44.855

[[trees]]
kind = "Beukenboom"
px = 175.39443100737344
py = 7.552160066797107
pz = 42.219

[[trees]]
kind = "Corner"
px = 173.79026697305912
py = 24.042198949670194
pz = 45.142

[[trees]]
kind = "Walnut"
px = 86.0
py = 6.0

